"""initial schema

Revision ID: a31cd025307e
Revises:
Create Date: 2026-09-06 17:27:46.197160
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a31cd025307e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("strategy", sa.String(length=20), nullable=False),
        sa.Column("training_start", sa.Date(), nullable=True),
        sa.Column("training_end", sa.Date(), nullable=True),
        sa.Column("validation_sharpe", sa.Float(), nullable=True),
        sa.Column("oos_sharpe", sa.Float(), nullable=True),
        sa.Column("oos_return", sa.Float(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_model_versions_name_active",
        "model_versions",
        ["model_name", "is_active"],
        unique=False,
    )
    op.create_table(
        "strategy_performance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("gross_return", sa.Float(), nullable=True),
        sa.Column("net_return", sa.Float(), nullable=True),
        sa.Column("sharpe", sa.Float(), nullable=True),
        sa.Column("sortino", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("num_trades", sa.Integer(), nullable=False),
        sa.Column("total_costs", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strategy", "date", name="uq_strategy_performance_strategy_date"),
    )
    op.create_index(
        "ix_strategy_performance_strategy_date",
        "strategy_performance",
        ["strategy", "date"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "account_cash",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trading_mode", sa.String(length=10), nullable=False),
        sa.Column("cash", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reserved", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_costs", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "trading_mode", name="uq_account_cash_user_mode"),
    )
    op.create_index(op.f("ix_account_cash_user_id"), "account_cash", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_user_created", "audit_logs", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "capital_allocations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("month_year", sa.String(length=7), nullable=False),
        sa.Column("contribution_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("longterm_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("swing_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("intraday_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cash_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("longterm_risk_pct", sa.Float(), nullable=False),
        sa.Column("swing_risk_pct", sa.Float(), nullable=False),
        sa.Column("intraday_risk_pct", sa.Float(), nullable=False),
        sa.Column("regime", sa.String(length=50), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "month_year", name="uq_capital_allocation_user_month"),
    )
    op.create_index(
        op.f("ix_capital_allocations_user_id"), "capital_allocations", ["user_id"], unique=False
    )
    op.create_index(
        "ix_capital_allocations_user_month",
        "capital_allocations",
        ["user_id", "month_year"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index(
        "ix_notifications_user_read", "notifications", ["user_id", "is_read"], unique=False
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("strategy", sa.String(length=20), nullable=False),
        sa.Column("entry_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("target_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("signal_strength", sa.Float(), nullable=True),
        sa.Column("sector", sa.String(length=60), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_user_id"), "positions", ["user_id"], unique=False)
    op.create_index("ix_positions_user_open", "positions", ["user_id", "is_open"], unique=False)
    op.create_index("ix_positions_user_symbol", "positions", ["user_id", "symbol"], unique=False)
    op.create_table(
        "reconciliation_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trading_mode", sa.String(length=10), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("trading_permitted", sa.Boolean(), nullable=False),
        sa.Column("discrepancy_count", sa.Integer(), nullable=False),
        sa.Column("unavailable", sa.JSON(), nullable=True),
        sa.Column("discrepancies", sa.JSON(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recon_user_created", "reconciliation_runs", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_runs_created_at"),
        "reconciliation_runs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_runs_user_id"), "reconciliation_runs", ["user_id"], unique=False
    )
    op.create_table(
        "risk_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("action_taken", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_risk_events_severity", "risk_events", ["severity"], unique=False)
    op.create_index(
        "ix_risk_events_user_created", "risk_events", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_risk_events_user_id"), "risk_events", ["user_id"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("strategy", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=5), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("expected_return", sa.Float(), nullable=True),
        sa.Column("expected_volatility", sa.Float(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column("model_name", sa.String(length=60), nullable=False),
        sa.Column("model_version", sa.String(length=30), nullable=False),
        sa.Column("features_snapshot", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acted_upon", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_signals_created", "signals", ["created_at"], unique=False)
    op.create_index(op.f("ix_signals_user_id"), "signals", ["user_id"], unique=False)
    op.create_index("ix_signals_user_strategy", "signals", ["user_id", "strategy"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("monthly_capital", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("risk_tolerance", sa.String(length=10), nullable=False),
        sa.Column("max_drawdown_pct", sa.Float(), nullable=False),
        sa.Column("intraday_enabled", sa.Boolean(), nullable=False),
        sa.Column("swing_enabled", sa.Boolean(), nullable=False),
        sa.Column("longterm_enabled", sa.Boolean(), nullable=False),
        sa.Column("max_positions", sa.Integer(), nullable=False),
        sa.Column("max_sector_exposure_pct", sa.Float(), nullable=False),
        sa.Column("max_single_stock_pct", sa.Float(), nullable=False),
        sa.Column("cash_reserve_pct", sa.Float(), nullable=False),
        sa.Column("auto_execution_enabled", sa.Boolean(), nullable=False),
        sa.Column("paper_trading_mode", sa.Boolean(), nullable=False),
        sa.Column("kill_switch_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=True)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id_broker", sa.String(length=100), nullable=True),
        sa.Column("client_order_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("transaction_type", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("filled_quantity", sa.Integer(), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("product", sa.String(length=10), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("order_type", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("strategy", sa.String(length=20), nullable=True),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("slippage_actual", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "client_order_id", name="uq_orders_user_client_order_id"),
    )
    op.create_index(op.f("ix_orders_order_id_broker"), "orders", ["order_id_broker"], unique=False)
    op.create_index("ix_orders_user_created", "orders", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_index("ix_orders_user_status", "orders", ["user_id", "status"], unique=False)
    op.create_table(
        "order_state_transitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("from_state", sa.String(length=30), nullable=True),
        sa.Column("to_state", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("filled_quantity", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_state_transitions_created_at"),
        "order_state_transitions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_state_transitions_order_id"),
        "order_state_transitions",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        "ix_ost_order_created", "order_state_transitions", ["order_id", "created_at"], unique=False
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("trade_id_broker", sa.String(length=100), nullable=True),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("transaction_type", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("brokerage", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("stt", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("exchange_charges", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gst", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("stamp_duty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sebi_charges", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_costs", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("net_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("strategy", sa.String(length=20), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "trade_id_broker", name="uq_trades_user_trade_id_broker"),
    )
    op.create_index(op.f("ix_trades_order_id"), "trades", ["order_id"], unique=False)
    op.create_index("ix_trades_user_created", "trades", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_trades_user_id"), "trades", ["user_id"], unique=False)
    op.create_index("ix_trades_user_strategy", "trades", ["user_id", "strategy"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trades_user_strategy", table_name="trades")
    op.drop_index(op.f("ix_trades_user_id"), table_name="trades")
    op.drop_index("ix_trades_user_created", table_name="trades")
    op.drop_index(op.f("ix_trades_order_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_ost_order_created", table_name="order_state_transitions")
    op.drop_index(
        op.f("ix_order_state_transitions_order_id"), table_name="order_state_transitions"
    )
    op.drop_index(
        op.f("ix_order_state_transitions_created_at"), table_name="order_state_transitions"
    )
    op.drop_table("order_state_transitions")
    op.drop_index("ix_orders_user_status", table_name="orders")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index("ix_orders_user_created", table_name="orders")
    op.drop_index(op.f("ix_orders_order_id_broker"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.drop_table("user_settings")
    op.drop_index("ix_signals_user_strategy", table_name="signals")
    op.drop_index(op.f("ix_signals_user_id"), table_name="signals")
    op.drop_index("ix_signals_created", table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_risk_events_user_id"), table_name="risk_events")
    op.drop_index("ix_risk_events_user_created", table_name="risk_events")
    op.drop_index("ix_risk_events_severity", table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_index(op.f("ix_reconciliation_runs_user_id"), table_name="reconciliation_runs")
    op.drop_index(op.f("ix_reconciliation_runs_created_at"), table_name="reconciliation_runs")
    op.drop_index("ix_recon_user_created", table_name="reconciliation_runs")
    op.drop_table("reconciliation_runs")
    op.drop_index("ix_positions_user_symbol", table_name="positions")
    op.drop_index("ix_positions_user_open", table_name="positions")
    op.drop_index(op.f("ix_positions_user_id"), table_name="positions")
    op.drop_table("positions")
    op.drop_index("ix_notifications_user_read", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_capital_allocations_user_month", table_name="capital_allocations")
    op.drop_index(op.f("ix_capital_allocations_user_id"), table_name="capital_allocations")
    op.drop_table("capital_allocations")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_user_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_account_cash_user_id"), table_name="account_cash")
    op.drop_table("account_cash")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_strategy_performance_strategy_date", table_name="strategy_performance")
    op.drop_table("strategy_performance")
    op.drop_index("ix_model_versions_name_active", table_name="model_versions")
    op.drop_table("model_versions")
    # ### end Alembic commands ###
